### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by lgjsdx** [lijinliangNiu/Spider-Baidu-Index#2]
Hello, I get the following error when I run the `main.py` code.

```Python
Traceback (most recent call last):
  File "D:/GithubProjects/Spider-Baidu-Index/main.py", line 21, in <module>
    for index_data in baidu_index.get_index():
  File "D:\GithubProjects\Spider-Baidu-Index\get_index.py", line 133, in get_index
    keywords=params_data['keywords']
  File "D:\GithubProjects\Spider-Baidu-Index\get_index.py", line 77, in get_encrypt_datas
    uniqid = datas['data']['uniqid']
TypeError: string indices must be integers
```
I changed the `COOKIE` that is copied from Baidu Index page. Would you please tell me how to fix it? Thank you very much.

**Comment by niu-lijinliang** [comment]
> Hello, I get the following error when I run the `main.py` code.
> 
> ```python
> Traceback (most recent call last):
>   File "D:/GithubProjects/Spider-Baidu-Index/main.py", line 21, in <module>
>     for index_data in baidu_index.get_index():
>   File "D:\GithubProjects\Spider-Baidu-Index\get_index.py", line 133, in get_index
>     keywords=params_data['keywords']
>   File "D:\GithubProjects\Spider-Baidu-Index\get_index.py", line 77, in get_encrypt_datas
>     uniqid = datas['data']['uniqid']
> TypeError: string indices must be integers
> ```
> 
> I changed the `COOKIE` that is copied from Baidu Index page. Would you please tell me how to fix it? Thank you very much.

我刚看了一下，请求参数已经改变了，还要修改一下。

**Comment by niu-lijinliang** [comment]
已解决
